workspace:
  base: /app

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  build:
      image: jonasfranz/flutter:master
      pull: true
      commands:
        - flutter packages get
        - make format-check
        - make build-all
        - mkdir apks
        - mv build/app/outputs/apk/*/*/*.apk apks
      when:
        event: [ push, tag ]

  test:
      image: jonasfranz/flutter:master
      pull: true
      commands:
        - make test
      when:
        event: [ push, tag, pull_request ]
 
  # Push the releases to our pseudo-s3-bucket
  release:
    image: plugins/s3:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: vikunja-app
    endpoint: https://storage.kolaente.de
    path_style: true
    strip_prefix: apks/
    source: apks/*
    target: /${DRONE_TAG##v}
    when:
      event: [ tag ]

  # Push the releases to our pseudo-s3-bucket
  release:
    image: plugins/s3:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: vikunja-app
    endpoint: https://storage.kolaente.de
    path_style: true
    strip_prefix: apks/
    source: apks/*
    target: /master
    when:
      event: [ push ]
      branch: [ master ]
